# Generated by Django 5.1.2 on 2024-10-22 23:46
import os

from django.db import migrations, connection


def load_data_from_sql(apps, schema_editor):
    file_path = os.path.join(os.path.dirname(__file__), '../../resources/data.sql')
    f = open(file_path)

    with connection.cursor() as c:
        for statement in f:
            if statement:
                c.execute(statement)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_data_from_sql),
    ]
