# Generated by Django 5.1.2 on 2024-10-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20241023_0032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="away_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_score",
            field=models.IntegerField(null=True),
        ),
    ]
