# Generated by Django 5.1.2 on 2024-10-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_game_away_score_alter_game_home_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bethouse',
            name='logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(null=True),
        ),
    ]
