# Generated by Django 5.1.2 on 2024-10-24 15:14
import os

from django.db import migrations, connection


def load_data_from_sql(apps, schema_editor):
    file_path = os.path.join(os.path.dirname(__file__), "../../resources/data_user.sql")
    f = open(file_path)

    with connection.cursor() as c:
        for statement in f:
            if statement:
                c.execute(statement)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_add_tier_data"),
    ]

    operations = [
        migrations.RunPython(load_data_from_sql),
    ]
